# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

jobs:
  include:
  - r: 3.5
    warnings_are_errors: true
  - r: 3.6
    warnings_are_errors: true
  - r: release
    warnings_are_errors: true
  - r: devel
    warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
  